disabled_projects:
    - "*"
enabled_projects:
    - nova: stable/icehouse
    - glance
    - keystone
passwords:
    admin: devstack
    rabbit: devstack
    mysql: devstack
    service: devstack
    database: devstack
local:
    fixed_range: 10.0.2.0/24
    service_token: devstack
    floating_range: 10.0.2.0/24
    fixed_network_size: 256
    screen_logdir: $DEST/logs/screen
    logfile: /home/stack/devstack/stack.log
    ceilometer_backend: mongo
    image_urls+: 'http://cloud.fedoraproject.org/fedora-20.x86_64.qcow2'
raw:
	[[post-config|$NOVA_CONF]]
	[DEFAULT]
	verbose=True
	debug=True
